before_script:
  - perl --version

variables:
  UNIT_SIMPLE_VERSION: "0.1.2"

stages:
  - test
  - demo
  - cpan-package
  - cpan-publish

test:unit-simple:
  stage: test
  script:
    - cd unit-simple
    - perl test.pl

demo:unit-simple:
  stage: demo
  script:
    - cd unit-simple
    - perl demo.pl

cpan-package:unit-simple:
  stage: cpan-package
  script:
    - cd unit-simple
    - sed -i "s#our \$VERSION = .*#our \$VERSION = \"$UNIT_SIMPLE_VERSION\";#g" unitSimple.pm
    - perl Makefile.PL
    - make manifest
    - make
    - make test
    - make dist
  artifacts:
    paths:
      - unit-simple/Cosmoloj-UnitSimple-$UNIT_SIMPLE_VERSION.tar.gz

cpan-publish:unit-simple:
  stage: cpan-publish
  when: manual
  script:
    - cd unit-simple
    - cpan-upload -u $CPAN_USERNAME -p $CPAN_PASSWORD Cosmoloj-UnitSimple-$UNIT_SIMPLE_VERSION.tar.gz
