name: unit_simple
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 5 * * 0'

jobs:
  test__unit_simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - working-directory: unit-simple
        run: perl test.pl
  demo__unit_simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - working-directory: unit-simple
        run: perl demo.pl
  cpan_package__unit_simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - working-directory: unit-simple
        run: |
          sed -i "s#our \$VERSION = .*#our \$VERSION = \"$UNIT_SIMPLE_VERSION\";#g" unitSimple.pm
          perl Makefile.PL
          make manifest
          make
          make test
          make dist
